# Generated by Django 5.1.1 on 2024-09-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shoes_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Product',
        ),
    ]
