# Generated by Django 5.1.1 on 2024-09-16 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_desc_barang_product_nama_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
